package com.lebang.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneBoxCallProto.proto

public final class PhoneBoxCallProto {
  private PhoneBoxCallProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhoneBoxCallOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string call = 1;
    /**
     * <code>required string call = 1;</code>
     */
    boolean hasCall();
    /**
     * <code>required string call = 1;</code>
     */
    String getCall();
    /**
     * <code>required string call = 1;</code>
     */
    com.google.protobuf.ByteString
        getCallBytes();
  }
  /**
   * Protobuf type {@code PhoneBoxCall}
   */
  public static final class PhoneBoxCall extends
      com.google.protobuf.GeneratedMessage
      implements PhoneBoxCallOrBuilder {
    // Use PhoneBoxCall.newBuilder() to construct.
    private PhoneBoxCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneBoxCall(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhoneBoxCall defaultInstance;
    public static PhoneBoxCall getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneBoxCall getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneBoxCall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              call_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PhoneBoxCallProto.internal_static_PhoneBoxCall_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PhoneBoxCallProto.internal_static_PhoneBoxCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PhoneBoxCall.class, Builder.class);
    }

    public static com.google.protobuf.Parser<PhoneBoxCall> PARSER =
        new com.google.protobuf.AbstractParser<PhoneBoxCall>() {
      public PhoneBoxCall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneBoxCall(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PhoneBoxCall> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string call = 1;
    public static final int CALL_FIELD_NUMBER = 1;
    private Object call_;
    /**
     * <code>required string call = 1;</code>
     */
    public boolean hasCall() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string call = 1;</code>
     */
    public String getCall() {
      Object ref = call_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          call_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string call = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCallBytes() {
      Object ref = call_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        call_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      call_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCall()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCallBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCallBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PhoneBoxCall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneBoxCall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneBoxCall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneBoxCall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneBoxCall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PhoneBoxCall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PhoneBoxCall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PhoneBoxCall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PhoneBoxCall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PhoneBoxCall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PhoneBoxCall prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PhoneBoxCall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PhoneBoxCallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PhoneBoxCallProto.internal_static_PhoneBoxCall_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PhoneBoxCallProto.internal_static_PhoneBoxCall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PhoneBoxCall.class, Builder.class);
      }

      // Construct using PhoneBoxCallProto.PhoneBoxCall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        call_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PhoneBoxCallProto.internal_static_PhoneBoxCall_descriptor;
      }

      public PhoneBoxCall getDefaultInstanceForType() {
        return PhoneBoxCall.getDefaultInstance();
      }

      public PhoneBoxCall build() {
        PhoneBoxCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PhoneBoxCall buildPartial() {
        PhoneBoxCall result = new PhoneBoxCall(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.call_ = call_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PhoneBoxCall) {
          return mergeFrom((PhoneBoxCall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PhoneBoxCall other) {
        if (other == PhoneBoxCall.getDefaultInstance()) return this;
        if (other.hasCall()) {
          bitField0_ |= 0x00000001;
          call_ = other.call_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCall()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PhoneBoxCall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PhoneBoxCall) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string call = 1;
      private Object call_ = "";
      /**
       * <code>required string call = 1;</code>
       */
      public boolean hasCall() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string call = 1;</code>
       */
      public String getCall() {
        Object ref = call_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          call_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string call = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCallBytes() {
        Object ref = call_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          call_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string call = 1;</code>
       */
      public Builder setCall(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        call_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string call = 1;</code>
       */
      public Builder clearCall() {
        bitField0_ = (bitField0_ & ~0x00000001);
        call_ = getDefaultInstance().getCall();
        onChanged();
        return this;
      }
      /**
       * <code>required string call = 1;</code>
       */
      public Builder setCallBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        call_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PhoneBoxCall)
    }

    static {
      defaultInstance = new PhoneBoxCall(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PhoneBoxCall)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PhoneBoxCall_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PhoneBoxCall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027PhoneBoxCallProto.proto\"\034\n\014PhoneBoxCal" +
      "l\022\014\n\004call\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PhoneBoxCall_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PhoneBoxCall_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PhoneBoxCall_descriptor,
              new String[] { "Call", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
